[environment]
env = "development"
version = "0.0.1"

[commands]
greet = "echo Hello, world"
clean = "dotnet clean"
build-project = ["clean", "build"]
publish = "dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true"
publish-linux = "dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true"
publish-mac = "dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained true"
combo = "echo hello && echo world"

[commands.build]
command = "dotnet"
args = ["build"]
