[environment]
env = "development"
version = "0.0.1"

[commands]
greet = "echo Hello, world"
clean = "dotnet clean"
build-project = ["clean", "build"]
lint = "dotnet fantomas ./src"
publish = "dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true -p:TargetFramework=net8.0"
publish-linux = "dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -p:TargetFramework=net8.0"
publish-mac = "dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained true -p:TargetFramework=net8.0"
install = "dotnet tool install --global --add-source ./nupkg fsrun"

[commands.build]
command = "dotnet"
args = ["build"]
